version: "3.8"
services:
  web:
    container_name: web-php
    restart: always  
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:  
      - ./API/:/var/www/
    depends_on:
      - db
  db:
    container_name: db-postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./API/:/var/www/
    depends_on:
      - web